name: Docker Image CI

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

jobs:
  build:
    environment: live
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - x64
          - arm64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          architecture: ${{ matrix.architecture }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          DOCKER_BUILD_KIT=1 DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --push \
          --build-arg=API_BASE_URL=${{ secrets.API_BASE_URL }} \
          -t docker.io/rootdavinalfa/animize-web:latest \
          -t docker.io/rootdavinalfa/animize-web:$(git rev-parse --short HEAD) \
          --platform=linux/amd64,linux/arm64 .
